### ISSUE TITLE
Frame drops and game crashes when used with MBB addon.

### ISSUE THREAD

**Issue by Sparcrypt** [DungFu/NauticusClassic#11]
Using the two addons together causes massive frame drops and game crashes, 

https://www.curseforge.com/wow/addons/mbb-classic

Disabling either addon fixes the issue and both work independently no issues.

Raised here as well: https://github.com/vallantv/MBBClassic/issues/5

**Comment by DungFu** [comment]
I submitted a PR to MBBClassic that should fix the issue

https://github.com/vallantv/MBBClassic/pull/6

**Comment by vallantv** [comment]
Merged the PR, i didn't have notifications on for that repo for some reason. Thanks!

**Comment by DungFu** [comment]
This should be fixed now with newest MBB version :)
