### ISSUE TITLE
No timer with Boat

### ISSUE THREAD

**Issue by hudsson** [DungFu/NauticusClassic#31]
Hello.
First, thank you for your job !
I play an orc with a game in french. I can see the timers for zep, but don't for the boat between Ratchet, The Barrens and Booty Bay, Stranglethorn Vale.
I have take this transport many times, but it's don't work.

Have a good day, and a good journey in Azeroth :p

**Comment by woopydalan** [comment]
@hudsson Hi this might be my fault, let me change the locale to French to look at it. In the code some of the zones need to have an exact match, and it looked like Blizz removed the (english name) from the zones i.e. Marécage d'Âprefange (Dustwallow Marsh)

**Comment by woopydalan** [comment]
@dungfu I logged onto the french client, when you are in the zone, the (english name) is present, but if you hover over it on the world map, there is no (english name). I don't know how your addon figures out the zone, but if its based on being in the zone and reading the zone name, then please accept my pull request
