### ISSUE TITLE
The version hosted on Curseforge/Twitch is not current.

### ISSUE THREAD

**Issue by thebear242** [DungFu/NauticusClassic#33]
I love this addon, and recommend it to my friends and guildies, most of whom use the Twitch desktop app, which pulls addons from Curseforge. Could you please update the Curseforge page to have the most current version? https://www.curseforge.com/wow/addons/nauticusclassic/files
Thank you!!
-Grohl of Grobbulus (Alliance)

**Comment by DungFu** [comment]
curseforge version has been updated
